SET FOREIGN_KEY_CHECKS = 0;

LOAD DATA local INFILE '__PATH__/emails.csv'
INTO TABLE `test-credo-email-verification`.`emails`
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

SET FOREIGN_KEY_CHECKS = 1;
