version: 0.2
phases:
  install:
    commands:
      - ls
      - env | sort
      - # run the ENTRYPOINT that AWS overrides
      - dockerd-entrypoint.sh
      - yarn install
  build:
    commands:
      - yarn lint
      - yarn test
