version: '2'

services :

  #############################################################################
  # MySQL
  database :
    image          : seancannon/dev_mysql
    hostname       : bw-dev-mysql
    container_name : bw_dev_mysql
    mem_limit      : 512m
    environment    :
      - "MYSQL_ROOT_PASSWORD=${CORE_DB_ROOT_PASSWORD}"
      - "TZ=${CORE_DB_TIMEZONE}"
    volumes        :
      - "${MYSQL_VOLUME_MOUNT}"
    tmpfs          :
      - "${MYSQL_TMPFS}"
    ports          :
      - "${CORE_DB_PORT}:3306"

  #############################################################################
  # PHPMyAdmin
  dbgui :
    image          : phpmyadmin/phpmyadmin
    container_name : phpmyadmin
    mem_limit      : 256m
    environment    :
      - "MYSQL_USERNAME=${CORE_DB_USER}"
      - "MYSQL_ROOT_PASSWORD=${CORE_DB_ROOT_PASSWORD}"
    links          :
      - database:db
    ports          :
      - "${PHPMYADMIN_PORT}:80"
    volumes:
      - "./tmp/env/${NODE_ENV}/phpmyadmin/sessions:/sessions"
